export interface IPartOfSpeech {
    enAbbrev: string;
    enName: string;
    esAbbrev: string;
    esName: string;
    tdAlternates?: string[];
}

export const partsOfSpeech: IPartOfSpeech[] = [
    { enAbbrev: 'n', enName: 'noun', esAbbrev: 's', esName: 'sustantivo', },
    { enAbbrev: 'pro', enName: 'pronoun', esAbbrev: 'pron', esName: 'pronombre', tdAlternates: ['pron'] },
    { enAbbrev: 'v', enName: 'verb', esAbbrev: 'v', esName: 'verbo', tdAlternates: ['verbo verbo'] },
    { enAbbrev: 'adj', enName: 'adjective', esAbbrev: 'adj', esName: 'adjetivo', tdAlternates: ['ajetivo'] },
    { enAbbrev: 'adv', enName: 'adverb', esAbbrev: 'adv', esName: 'adverbio', },
    { enAbbrev: 'prep', enName: 'preposition', esAbbrev: 'prep', esName: 'preposición', },
    { enAbbrev: 'conj', enName: 'conjunction', esAbbrev: 'conj', esName: 'conjunción', },
    { enAbbrev: 'det', enName: 'determiner', esAbbrev: 'det', esName: 'determinante', },
    { enAbbrev: 'int', enName: 'interjection', esAbbrev: 'interj', esName: 'interjección', tdAlternates: ['inter']},
    { enAbbrev: 'no', enName: 'number', esAbbrev: 'no', esName: 'número', tdAlternates: ['numero', 'nunero'] },
    { enAbbrev: 'dem', enName: 'demonstrative', esAbbrev: 'dem', esName: 'demostrativo', },
    { enAbbrev: 'n pl', enName: 'plural noun', esAbbrev: 's pl', esName: 'sustantivo plural', tdAlternates: ['noun, plural']},
    { enAbbrev: 'phr', enName: 'phrase', esAbbrev: 'fr', esName: 'frase', tdAlternates: ['̃frase'] },
    { enAbbrev: 'p', enName: 'particle', esAbbrev: 'p', esName: 'partícula', tdAlternates: ['part']},
    { enAbbrev: 'neg', enName: 'negative', esAbbrev: 'neg', esName: 'negativo', tdAlternates: ['negative particle', 'negation'] },
    { enAbbrev: 'quan', enName: 'quantifier', esAbbrev: 'quan', esName: 'cuantificador', tdAlternates: ['quant'] },
    { enAbbrev: 'rel', enName: 'relative', esAbbrev: 'rel', esName: 'relativo', },
    { enAbbrev: 'v.aux', enName: 'auxiliary verb', esAbbrev: 'v.aux', esName: 'verbo auxiliar', },
    { enAbbrev: 'dem.a', enName: 'animate demonstrative', esAbbrev: 'dem.a', esName: 'demostrativo animado', },
    { enAbbrev: 'dem.i', enName: 'inanimate demonstrative', esAbbrev: 'dem.i', esName: 'demostrativo inanimado', },
    { enAbbrev: 'dem.loc', enName: 'locative demonstrative', esAbbrev: 'dem.loc', esName: 'demostrativo locativo', },
    { enAbbrev: 'dim', enName: 'diminutive', esAbbrev: 'dim', esName: 'diminutivo', },
    { enAbbrev: 'na', enName: 'animate noun', esAbbrev: 'sa', esName: 'sustantivo animado', },
    { enAbbrev: 'ni', enName: 'inanimate noun', esAbbrev: 'si', esName: 'sustantivo inanimado', },
    { enAbbrev: 'pl', enName: 'plural', esAbbrev: 'pl', esName: 'plural', },
    { enAbbrev: 'pn', enName: 'prenoun', esAbbrev: 'pn', esName: 'prenombre', },
    { enAbbrev: 'pv', enName: 'preverb', esAbbrev: 'pv', esName: 'preverbo', },
    { enAbbrev: 'pn/v', enName: 'prenoun / preverb', esAbbrev: 'pn/v', esName: 'prenombre / preverbo', },
    { enAbbrev: 'pro.a', enName: 'animate pronoun', esAbbrev: 'pro.a', esName: 'pronombre animado', },
    { enAbbrev: 'pro.i', enName: 'inanimate pronoun', esAbbrev: 'pro.i', esName: 'pronombre inanimado', },
    { enAbbrev: 'redup', enName: 'reduplication', esAbbrev: 'redup', esName: 'reduplicación', },
    { enAbbrev: 'refl', enName: 'reflexive', esAbbrev: 'refl', esName: 'reflexivo', },
    { enAbbrev: 'vai', enName: 'animate intransitive verb', esAbbrev: 'vai', esName: 'verbo intransitivo animado', },
    { enAbbrev: 'vai/ii', enName: 'animate / inanimate intransitive verb', esAbbrev: 'vai/ii', esName: 'verbo intransitivo animado / inanimado', },
    { enAbbrev: 'vii', enName: 'inanimate intransitive verb', esAbbrev: 'vii', esName: 'verbo intransitivo inanimado', },
    { enAbbrev: 'vta', enName: 'transitive animate verb', esAbbrev: 'vta', esName: 'verbo transitivo animado ', },
    { enAbbrev: 'vti', enName: 'transitive inanimate verb', esAbbrev: 'vti', esName: 'verbo transitivo inanimado', },
    { enAbbrev: 'imp', enName: 'imperative/command marker', esAbbrev: 'imp', esName: 'marcador de imperativo', tdAlternates: ['imperative'] },
    { enAbbrev: 'pref', enName: 'prefix', esAbbrev: 'pref', esName: 'prefijo', },
    { enAbbrev: 'punc', enName: 'punctuation', esAbbrev: 'punc', esName: 'puntuación', },
    { enAbbrev: 'suff', enName: 'suffix', esAbbrev: 'suff', esName: 'sufijo', },
    { enAbbrev: 'vt', enName: 'transitive verb', esAbbrev: 'vt', esName: 'verbo transitivo', },
    { enAbbrev: 'vi', enName: 'intransitive verb', esAbbrev: 'vi', esName: 'verbo intransitivo', },
    { enAbbrev: 'comp', enName: 'complement(izer)', esAbbrev: 'comp', esName: 'complementor', },
    { enAbbrev: 'cpd', enName: 'compound', esAbbrev: '', esName: 'compuesto', },
    { enAbbrev: 'imit', enName: 'imitative', esAbbrev: 'imit', esName: 'imitativo', },
    { enAbbrev: 'pple', enName: 'participle', esAbbrev: 'part', esName: 'participio', },
    { enAbbrev: 'sent', enName: 'sentence', esAbbrev: '', esName: 'frase completa', },
    { enAbbrev: 'pr.n', enName: 'proper noun', esAbbrev: '', esName: 'sustantivo propio', tdAlternates: ['proper name'] },
    { enAbbrev: 'np', enName: 'noun phrase', esAbbrev: '', esName: 'frase nominal', tdAlternates: ['noun; phrase'] },
    { enAbbrev: 'vp', enName: 'verb phrase', esAbbrev: '', esName: 'frase verbal', },
    { enAbbrev: 'ap', enName: 'adjective phrase', esAbbrev: '', esName: 'frase adjetiva', tdAlternates: ['frase adjetival', 'adjectival phrase'] },
    { enAbbrev: 'adv.p', enName: 'adverb phrase', esAbbrev: '', esName: 'frase adverbial', },
    { enAbbrev: 'pl.pro', enName: 'plural pronoun', esAbbrev: 'pro.pl', esName: 'pronombre plural', },
    { enAbbrev: 'q', enName: 'question marker', esAbbrev: 'q', esName: 'marcador de preguntas', tdAlternates: ['question word', 'interrogative particle'] }, // 'question word found in old Gta TD  
    { enAbbrev: 'ger', enName: 'gerund', esAbbrev: 'ger', esName: 'gerundio', },
    { enAbbrev: 'art', enName: 'article', esAbbrev: 'art', esName: 'artículo', },
    { enAbbrev: 'post', enName: 'post-position', esAbbrev: 'post', esName: 'posición posterior', },
    { enAbbrev: 'e.w', enName: 'entry word / discourse particle', esAbbrev: 'e.w', esName: 'palabra de entrada / partícula del discurso', },
    { enAbbrev: 'm.w', enName: 'measure word', esAbbrev: '', esName: 'palabra de medida', },
    { enAbbrev: 'msd', enName: 'masdar', esAbbrev: 'msd', esName: 'masdar', },
    { enAbbrev: 'idf', enName: 'idafa', esAbbrev: 'idf', esName: 'idafa', },
    { enAbbrev: 'v.prdg', enName: 'verbal paradigm', esAbbrev: '', esName: 'paradigma verbal', },
    { enAbbrev: 'acr', enName: 'acronym', esAbbrev: '', esName: 'abreviatura', },
    { enAbbrev: 'cntr', enName: 'contraction', esAbbrev: 'cntr', esName: 'contracción', },
    { enAbbrev: 'num', enName: 'numeral', esAbbrev: 'num', esName: 'numeral', },
    { enAbbrev: 'act.v', enName: 'active verb', esAbbrev: 'v.act', esName: 'verbo activo', },
    { enAbbrev: 'stat.v', enName: 'stative verb', esAbbrev: 'v.est', esName: 'verbo estativo', },
    { enAbbrev: 'caus.v', enName: 'causative verb', esAbbrev: 'v.caus', esName: 'verbo causativo', },
    { enAbbrev: 'v.suff', enName: 'verb suffix', esAbbrev: 'suf.v', esName: 'sufijo verbal', },
    { enAbbrev: 'n.suff', enName: 'noun suffix', esAbbrev: 'suj.s', esName: 'sufijo sustantivo', },
    { enAbbrev: 'n.pref', enName: 'noun prefix', esAbbrev: 'pref.s', esName: 'prefijo de sustantivo', },
    { enAbbrev: 'v.pref', enName: 'verb prefix', esAbbrev: 'pref.v', esName: 'prefijo verbal', },
    { enAbbrev: 'ideo', enName: 'ideophone (onomatoepia / expressives)', esAbbrev: 'ideo', esName: 'ideófono (onomatoepia / expresivos)', },
    { enAbbrev: 'clf', enName: 'classifier / quantifier', esAbbrev: 'clf', esName: 'clasificador / cuantificador', },
    { enAbbrev: 'tns', enName: 'tense marker', esAbbrev: 'tns', esName: 'marcador de tensión', },
    { enAbbrev: 'asp', enName: 'aspect marker', esAbbrev: 'asp', esName: 'marcador de aspecto', },
    { enAbbrev: 'mod', enName: 'mood marker', esAbbrev: 'mod', esName: 'indicador de humor', },
    { enAbbrev: 'n.cls', enName: 'noun class marker', esAbbrev: 'n.cls', esName: 'marcador de clase de sustantivo', },
    { enAbbrev: 'quot', enName: 'quotative', esAbbrev: 'quot', esName: 'quotativo', },
]



