export interface IPartOfSpeech {
    official: boolean;
    enAbbrev: string;
    enName: string;
    esAbbrev: string;
    esName: string;
    tdAlternates?: string[];
}

export const partsOfSpeech: IPartOfSpeech[] = [
    { official: true, enAbbrev: 'n', enName: 'noun', esAbbrev: 's', esName: 'sustantivo', tdAlternates: ['1. Noun', 'nominal', 'letter name'] },
    { official: true, enAbbrev: 'pro', enName: 'pronoun', esAbbrev: 'pron', esName: 'pronombre', tdAlternates: ['plural pronoun'] },
    { official: true, enAbbrev: 'v', enName: 'verb', esAbbrev: 'v', esName: 'verbo', tdAlternates: ['verbo verbo', 'verb, imperfect', 'verb, defective', 'imperative verb neg.'] },
    { official: true, enAbbrev: 'adj', enName: 'adjective', esAbbrev: 'adj', esName: 'adjetivo', tdAlternates: ['ajetivo'] },
    { official: true, enAbbrev: 'adv', enName: 'adverb', esAbbrev: 'adv', esName: 'adverbio', tdAlternates: [] },
    { official: true, enAbbrev: 'prep', enName: 'preposition', esAbbrev: 'prep', esName: 'preposición', tdAlternates: [] },
    { official: true, enAbbrev: 'conj', enName: 'conjunction', esAbbrev: 'conj', esName: 'conjunción', tdAlternates: [] },
    { official: true, enAbbrev: 'det', enName: 'determiner', esAbbrev: 'det', esName: 'determinante', tdAlternates: [] },
    { official: true, enAbbrev: 'int', enName: 'interjection', esAbbrev: 'interj', esName: 'interjección', tdAlternates: ['inter', 'negative interjection'] },
    { official: true, enAbbrev: 'no', enName: 'number', esAbbrev: 'nro', esName: 'número', tdAlternates: ['numero', 'nunero'] },
    { official: true, enAbbrev: 'dem', enName: 'demonstrative', esAbbrev: 'dem', esName: 'demostrativo', tdAlternates: [] },
    { official: true, enAbbrev: 'n pl', enName: 'plural noun', esAbbrev: 's.pl', esName: 'sustantivo plural', tdAlternates: ['noun, plural'] },
    { official: true, enAbbrev: 'phr', enName: 'phrase', esAbbrev: 'fr', esName: 'frase', tdAlternates: ['̃frase'] },
    { official: true, enAbbrev: 'p', enName: 'particle', esAbbrev: 'part', esName: 'partícula', tdAlternates: ['part'] },
    { official: true, enAbbrev: 'neg', enName: 'negative', esAbbrev: 'neg', esName: 'negativo', tdAlternates: ['negative particle', 'negation'] },
    { official: true, enAbbrev: 'quan', enName: 'quantifier', esAbbrev: 'cuant', esName: 'cuantificador', tdAlternates: ['quant'] },
    { official: false, enAbbrev: 'rel', enName: 'relative', esAbbrev: 'rel', esName: 'relativo', tdAlternates: [] },
    { official: true, enAbbrev: 'v.aux', enName: 'auxiliary verb', esAbbrev: 'v.aux', esName: 'verbo auxiliar', tdAlternates: [] },
    { official: true, enAbbrev: 'dem.a', enName: 'animate demonstrative', esAbbrev: 'dem.anim', esName: 'demostrativo animado', tdAlternates: [] },
    { official: true, enAbbrev: 'dem.i', enName: 'inanimate demonstrative', esAbbrev: 'dem.inam', esName: 'demostrativo inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'dem.loc', enName: 'locative demonstrative', esAbbrev: 'dem.loc', esName: 'demostrativo locativo', tdAlternates: [] },
    { official: false, enAbbrev: 'dim', enName: 'diminutive', esAbbrev: 'dim', esName: 'diminutivo', tdAlternates: [] },
    { official: true, enAbbrev: 'na', enName: 'animate noun', esAbbrev: 's.anim', esName: 'sustantivo animado', tdAlternates: [] },
    { official: true, enAbbrev: 'ni', enName: 'inanimate noun', esAbbrev: 's.inam', esName: 'sustantivo inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'pl', enName: 'plural', esAbbrev: 'pl', esName: 'plural', tdAlternates: [] },
    { official: true, enAbbrev: 'pn', enName: 'prenoun', esAbbrev: 'pren', esName: 'prenombre', tdAlternates: [] },
    { official: true, enAbbrev: 'pv', enName: 'preverb', esAbbrev: 'prev', esName: 'preverbo', tdAlternates: [] },
    { official: true, enAbbrev: 'pn/v', enName: 'prenoun / preverb', esAbbrev: 'pren/prev', esName: 'prenombre / preverbo', tdAlternates: [] },
    { official: true, enAbbrev: 'pro.a', enName: 'animate pronoun', esAbbrev: 'pro.anim', esName: 'pronombre animado', tdAlternates: [] },
    { official: true, enAbbrev: 'pro.i', enName: 'inanimate pronoun', esAbbrev: 'pro.inam', esName: 'pronombre inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'redup', enName: 'reduplication', esAbbrev: 'redup', esName: 'reduplicación', tdAlternates: [] },
    { official: true, enAbbrev: 'refl', enName: 'reflexive', esAbbrev: 'refl', esName: 'reflexivo', tdAlternates: [] },
    { official: true, enAbbrev: 'vai', enName: 'animate intransitive verb', esAbbrev: 'ver.intr.anim', esName: 'verbo intransitivo animado', tdAlternates: [] },
    { official: false, enAbbrev: 'vai/ii', enName: 'animate / inanimate intransitive verb', esAbbrev: 'ver.intr.anim/inam', esName: 'verbo intransitivo animado / inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'vii', enName: 'inanimate intransitive verb', esAbbrev: 'ver.intr.inam', esName: 'verbo intransitivo inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'vta', enName: 'transitive animate verb', esAbbrev: 'vta', esName: 'verbo transitivo animado ', tdAlternates: [] },
    { official: true, enAbbrev: 'vti', enName: 'transitive inanimate verb', esAbbrev: 'vti', esName: 'verbo transitivo inanimado', tdAlternates: [] },
    { official: true, enAbbrev: 'imp', enName: 'imperative/command marker', esAbbrev: 'imp', esName: 'imperativo', tdAlternates: ['imperative'] },
    { official: false, enAbbrev: 'pref', enName: 'prefix', esAbbrev: 'pref', esName: 'prefijo', tdAlternates: [] },
    { official: true, enAbbrev: 'punc', enName: 'punctuation', esAbbrev: 'ort', esName: 'ortografía', tdAlternates: [] },
    { official: false, enAbbrev: 'suff', enName: 'suffix', esAbbrev: 'suf', esName: 'sufijo', tdAlternates: [] },
    { official: true, enAbbrev: 'vt', enName: 'transitive verb', esAbbrev: 'vt', esName: 'verbo transitivo', tdAlternates: [] },
    { official: true, enAbbrev: 'vi', enName: 'intransitive verb', esAbbrev: 'vi', esName: 'verbo intransitivo', tdAlternates: [] },
    { official: true, enAbbrev: 'comp', enName: 'complement(izer)', esAbbrev: 'com', esName: 'complement(ador)', tdAlternates: [] },
    { official: true, enAbbrev: 'cpd', enName: 'compound', esAbbrev: 'comp', esName: 'compuesto', tdAlternates: [] },
    { official: true, enAbbrev: 'pple', enName: 'participle', esAbbrev: 'ppio', esName: 'participio', tdAlternates: [] },
    { official: true, enAbbrev: 'sent', enName: 'sentence', esAbbrev: 'o', esName: 'oración', tdAlternates: ['interrogative sentence', 'sentnece, interrogative'] },
    { official: true, enAbbrev: 'pr.n', enName: 'proper noun', esAbbrev: 'nom.pr', esName: 'nombre proprio', tdAlternates: ['proper name'] },
    { official: true, enAbbrev: 'np', enName: 'noun phrase', esAbbrev: 'fr.n', esName: 'frase nominal', tdAlternates: ['noun; phrase'] },
    { official: true, enAbbrev: 'vp', enName: 'verb phrase', esAbbrev: 'fr.v', esName: 'frase verbal', tdAlternates: [] },
    { official: true, enAbbrev: 'ap', enName: 'adjective phrase', esAbbrev: 'fr.adj', esName: 'frase adjetival', tdAlternates: ['frase adjetival', 'adjectival phrase'] },
    { official: true, enAbbrev: 'adv.p', enName: 'adverb phrase', esAbbrev: 'fr.adv', esName: 'frase adverbial', tdAlternates: [] },
    { official: true, enAbbrev: 'q', enName: 'question marker', esAbbrev: 'preg', esName: 'marca de pregunta', tdAlternates: ['question word', 'interrogative particle', 'interrogative'] },
    { official: true, enAbbrev: 'ger', enName: 'gerund', esAbbrev: 'ger', esName: 'gerundio', tdAlternates: [] },
    { official: true, enAbbrev: 'art', enName: 'article', esAbbrev: 'art', esName: 'artículo', tdAlternates: [] },
    { official: true, enAbbrev: 'post', enName: 'postposition', esAbbrev: 'post', esName: 'postposición', tdAlternates: ['postp'] },
    { official: true, enAbbrev: 'e.w', enName: 'entry word / discourse particle', esAbbrev: 'pal', esName: 'palabra de entrada / partícula del discurso', tdAlternates: [] },
    { official: true, enAbbrev: 'm.w', enName: 'measure word', esAbbrev: 'med', esName: 'término de medición', tdAlternates: [] },
    { official: true, enAbbrev: 'msd', enName: 'masdar', esAbbrev: 'msd', esName: 'masdar', tdAlternates: [] },
    { official: true, enAbbrev: 'idf', enName: 'idafa', esAbbrev: 'idf', esName: 'idafa', tdAlternates: [] },
    { official: false, enAbbrev: 'v.prdg', enName: 'verbal paradigm', esAbbrev: 'pdma.verb', esName: 'paradigma verbal', tdAlternates: [] },
    { official: true, enAbbrev: 'acr', enName: 'acronym', esAbbrev: 'acr', esName: 'acrónimo', tdAlternates: [] },
    { official: true, enAbbrev: 'cntr', enName: 'contraction', esAbbrev: 'cntr', esName: 'contracción', tdAlternates: [] },
    { official: true, enAbbrev: 'num', enName: 'numeral', esAbbrev: 'num', esName: 'numeral', tdAlternates: [] },
    { official: true, enAbbrev: 'act.v', enName: 'active verb', esAbbrev: 'v.act', esName: 'verbo activo', tdAlternates: [] },
    { official: true, enAbbrev: 'stat.v', enName: 'stative verb', esAbbrev: 'v.est', esName: 'verbo estativo', tdAlternates: [] },
    { official: true, enAbbrev: 'caus.v', enName: 'causative verb', esAbbrev: 'v.caus', esName: 'verbo causativo', tdAlternates: [] },
    { official: false, enAbbrev: 'v.suff', enName: 'verb suffix', esAbbrev: 'suf.v', esName: 'sufijo verbal', tdAlternates: [] },
    { official: false, enAbbrev: 'n.suff', enName: 'noun suffix', esAbbrev: 'suj.s', esName: 'sufijo sustantivo', tdAlternates: [] },
    { official: false, enAbbrev: 'n.pref', enName: 'noun prefix', esAbbrev: 'pref.s', esName: 'prefijo de sustantivo', tdAlternates: [] },
    { official: false, enAbbrev: 'v.pref', enName: 'verb prefix', esAbbrev: 'pref.v', esName: 'prefijo verbal', tdAlternates: [] },
    { official: true, enAbbrev: 'ideo', enName: 'ideophone (onomatoepia / expressives)', esAbbrev: 'ideo', esName: 'ideófono (onomatopeya / expresivos)', tdAlternates: ['imitative'] },
    { official: true, enAbbrev: 'clf', enName: 'classifier', esAbbrev: 'clf', esName: 'clasificador', tdAlternates: [] },
    { official: true, enAbbrev: 'tns', enName: 'tense marker', esAbbrev: 'm.tiemp', esName: 'marcador de tiempo', tdAlternates: [] },
    { official: true, enAbbrev: 'asp', enName: 'aspect marker', esAbbrev: 'asp', esName: 'marcador de aspecto', tdAlternates: [] },
    { official: true, enAbbrev: 'mod', enName: 'mood marker', esAbbrev: 'mod', esName: 'indicador de modo', tdAlternates: [] },
    { official: true, enAbbrev: 'n.cls', enName: 'noun class marker', esAbbrev: 's.cls', esName: 'marcador de clase de sustantivo', tdAlternates: [] },
    { official: true, enAbbrev: 'quot', enName: 'quotative', esAbbrev: 'cuot', esName: 'cuotativo', tdAlternates: [] },
    { official: true, enAbbrev: 'adp', enName: 'adposition', esAbbrev: 'adpos', esName: 'adposición', tdAlternates: [] },
    { official: true, enAbbrev: 'def', enName: 'definite article', esAbbrev: 'déf', esName: 'artículo definido', tdAlternates: [] },
    { official: true, enAbbrev: 'indf', enName: 'indefinite article', esAbbrev: 'indf', esName: 'artículo indefinido', tdAlternates: [] },
    { official: true, enAbbrev: 'indfpro', enName: 'Indefinite pronoun', esAbbrev: 'indf', esName: 'pronombre indefinido', tdAlternates: [] },
    { official: true, enAbbrev: 'pers', enName: 'personal pronoun', esAbbrev: 'pers', esName: 'pronombre personal', tdAlternates: [] },
    { official: true, enAbbrev: 'poss', enName: 'possessive pronoun', esAbbrev: 'pos', esName: 'pronombre posesivo', tdAlternates: [] },
    { official: true, enAbbrev: 'refl', enName: 'reflexive pronoun', esAbbrev: 'pro.refl', esName: 'pronombre reflexivo', tdAlternates: [] },
    { official: true, enAbbrev: 'relpro', enName: 'relative pronoun', esAbbrev: 'rel', esName: 'pronombre relativo', tdAlternates: [] },
    { official: true, enAbbrev: 'vd', enName: 'ditransitive verb', esAbbrev: 'vb', esName: 'verbo bitransitivo', tdAlternates: [] },
    { official: false, enAbbrev: 'interr.pro', enName: 'interrogative pronoun', esAbbrev: '', esName: 'pronombre interrogativo', tdAlternates: [] },
    { official: false, enAbbrev: 'cop', enName: 'copula', esAbbrev: 'cop', esName: 'copula', tdAlternates: [] },
    { official: false, enAbbrev: 'imp.verb', enName: 'imperative verb', esAbbrev: '', esName: 'verbo imperativo', tdAlternates: [] },
    { official: false, enAbbrev: 'phr.v', enName: 'phrasal verb', esAbbrev: '', esName: '', tdAlternates: ['phrasal imperative verb'] },
    { official: false, enAbbrev: 'inal.n', enName: 'inalienable noun', esAbbrev: '', esName: 'sustantivo inalienable', tdAlternates: ['sustantivo inalenable', 'always possessed noun'] },
    { official: false, enAbbrev: 'rel.n', enName: 'relational noun', esAbbrev: '', esName: 'sustantivo relacional', tdAlternates: [] },
    { official: false, enAbbrev: 'v.n', enName: 'verbal noun', esAbbrev: '', esName: 'sustantivo verbal', tdAlternates: [] },
]
